name: _error
timestamp: 1586941580
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1499244726
positions: {  }
sections:
  error: Error
  offcanvas: Offcanvas
particles:
  custom:
    custom-5794: 'Error Content'
    custom-9555: 'Homepage Button'
  logo:
    logo-6758: 'Logo / Image'
  messages:
    system-messages-3346: 'System Messages'
  content:
    system-content-9621: 'Page Content'
  mobile-menu:
    mobile-menu-1335: Mobile-menu
inherit:
  default:
    offcanvas: offcanvas
    mobile-menu-1335: mobile-menu-2118
