name: '9'
timestamp: 1586941291
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1586941290
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-6954: Logo
    logo-9119: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
    position-position-1647: Header
    position-position-7923: Breadcrumbs
    position-position-6951: Footer
  menu:
    menu-6061: Menu
    menu-3669: Menu
  messages:
    system-messages-3769: 'System Messages'
    system-messages-8335: 'System Messages'
  content:
    system-content-6757: 'Page Content'
    system-content-1689: 'Page Content'
  copyright:
    copyright-5419: Copyright
    copyright-8787: Copyright
  spacer:
    spacer-2425: Spacer
    spacer-3270: Spacer
  branding:
    branding-7597: Branding
    branding-3330: Branding
  mobile-menu:
    mobile-menu-2704: Mobile-menu
    mobile-menu-8165: Mobile-menu
inherit:
  default:
    header: header
    logo-6954: logo-6954
    position-header: position-header
    navigation: navigation
    menu-6061: menu-6061
    main: main
    position-breadcrumbs: position-breadcrumbs
    system-messages-3769: system-messages-3769
    system-content-6757: system-content-6757
    footer: footer
    position-footer: position-footer
    copyright-5419: copyright-5419
    spacer-2425: spacer-2425
    branding-7597: branding-7597
    offcanvas: offcanvas
    mobile-menu-2704: mobile-menu-2704
    logo-9119: logo-6954
    position-position-1647: position-header
    menu-3669: menu-6061
    position-position-7923: position-breadcrumbs
    system-messages-8335: system-messages-3769
    system-content-1689: system-content-6757
    position-position-6951: position-footer
    copyright-8787: copyright-5419
    spacer-3270: spacer-2425
    branding-3330: branding-7597
    mobile-menu-8165: mobile-menu-2704
