name: _body_only
timestamp: 1586941580
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1493247591
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-2818: 'System Messages'
  content:
    system-content-1029: 'Page Content'
inherit: {  }
